spring.application.name=Elearning
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:mysql://localhost:3306/elearning?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


app.jwt.secret=doi-chuoi-nay-thanh-random-string-that-dai-toi-thieu-32-ky-tu
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.cache.type=redis
vnpay.tmn-code=PULD6BQ0
vnpay.hash-secret=GSMZUZVVYNNRYSSNPIODVFIFCMNZRCCB
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=https://bikini-feb-none-late.trycloudflare.com/api/v1/payments/vnpay-ipn
